<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-03T00:07:33 PST" name="Suite" finished-at="2021-02-03T00:07:35 PST" duration-ms="2311">
    <groups>
    </groups>
    <test started-at="2021-02-03T00:07:33 PST" name="Test1" finished-at="2021-02-03T00:07:35 PST" duration-ms="2311">
      <class name="restbasic1.restbasicRequest.getRequestValidation1">
        <test-method signature="getValidation_ResponseHeader()[pri:0, instance:restbasic1.restbasicRequest.getRequestValidation1@470734c3]" started-at="2021-02-03T00:07:35 PST" name="getValidation_ResponseHeader" finished-at="2021-02-03T00:07:35 PST" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getValidation_ResponseHeader -->
      </class> <!-- restbasic1.restbasicRequest.getRequestValidation1 -->
      <class name="restbasic1.restbasicRequest.postRequest">
        <test-method signature="creatUserTest()[pri:0, instance:restbasic1.restbasicRequest.postRequest@2cf3d63b]" started-at="2021-02-03T00:07:35 PST" name="creatUserTest" finished-at="2021-02-03T00:07:35 PST" duration-ms="67" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatUserTest -->
      </class> <!-- restbasic1.restbasicRequest.postRequest -->
      <class name="restbasic1.restbasicRequest.getRequestValidation">
        <test-method signature="getValidation_StatusCode()[pri:0, instance:restbasic1.restbasicRequest.getRequestValidation@4b741d6d]" started-at="2021-02-03T00:07:35 PST" name="getValidation_StatusCode" finished-at="2021-02-03T00:07:35 PST" duration-ms="49" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getValidation_StatusCode -->
      </class> <!-- restbasic1.restbasicRequest.getRequestValidation -->
      <class name="restbasic1.restbasicRequest.getRequestValidation2">
        <test-method signature="getValidation_ResponseBody()[pri:0, instance:restbasic1.restbasicRequest.getRequestValidation2@2eae8e6e]" started-at="2021-02-03T00:07:35 PST" name="getValidation_ResponseBody" finished-at="2021-02-03T00:07:35 PST" duration-ms="59" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at restbasic1.restbasicRequest.getRequestValidation2.getValidation_ResponseBody(getRequestValidation2.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getValidation_ResponseBody -->
      </class> <!-- restbasic1.restbasicRequest.getRequestValidation2 -->
      <class name="restbasic1.restbasicRequest.DeleteRequest">
        <test-method signature="delete_request()[pri:0, instance:restbasic1.restbasicRequest.DeleteRequest@15bb5034]" started-at="2021-02-03T00:07:33 PST" name="delete_request" finished-at="2021-02-03T00:07:35 PST" duration-ms="1702" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete_request -->
      </class> <!-- restbasic1.restbasicRequest.DeleteRequest -->
      <class name="restbasic1.restbasicRequest.getRequest">
        <test-method signature="getStatusCode()[pri:0, instance:restbasic1.restbasicRequest.getRequest@8f2ef19]" started-at="2021-02-03T00:07:35 PST" name="getStatusCode" finished-at="2021-02-03T00:07:35 PST" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getStatusCode -->
      </class> <!-- restbasic1.restbasicRequest.getRequest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
